// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Ptzj7azlRvmYh1wmbqUZrJnbtm5Hq-s',
    appId: '1:351397882073:web:4efccc43950b87994f36c8',
    messagingSenderId: '351397882073',
    projectId: 'greenconnectplatform',
    authDomain: 'greenconnectplatform.firebaseapp.com',
    storageBucket: 'greenconnectplatform.firebasestorage.app',
    measurementId: 'G-E7663CP817',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5UIDhwBDiiUz4Abm1b3HSDYGjKncz_Do',
    appId: '1:351397882073:android:d67b944abfc1139d4f36c8',
    messagingSenderId: '351397882073',
    projectId: 'greenconnectplatform',
    storageBucket: 'greenconnectplatform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcyeJyuYogNh_MaPdzukf3mhntwLfqZ04',
    appId: '1:351397882073:ios:1caf600438f2fb244f36c8',
    messagingSenderId: '351397882073',
    projectId: 'greenconnectplatform',
    storageBucket: 'greenconnectplatform.firebasestorage.app',
    iosBundleId: 'com.greenconnect.platform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcyeJyuYogNh_MaPdzukf3mhntwLfqZ04',
    appId: '1:351397882073:ios:5650ce82709c031b4f36c8',
    messagingSenderId: '351397882073',
    projectId: 'greenconnectplatform',
    storageBucket: 'greenconnectplatform.firebasestorage.app',
    iosBundleId: 'com.example.greenConnectMb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Ptzj7azlRvmYh1wmbqUZrJnbtm5Hq-s',
    appId: '1:351397882073:web:edd1a727caf6a2154f36c8',
    messagingSenderId: '351397882073',
    projectId: 'greenconnectplatform',
    authDomain: 'greenconnectplatform.firebaseapp.com',
    storageBucket: 'greenconnectplatform.firebasestorage.app',
    measurementId: 'G-H6FB7DM0LZ',
  );
}
